'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsPersonas_Homo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class SRValidationException
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class telefono
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroField As Long
        
        Private numeroFieldSpecified As Boolean
        
        Private tipoLineaField As String
        
        Private tipoTelefonoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
                Me.RaisePropertyChanged("numero")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroSpecified() As Boolean
            Get
                Return Me.numeroFieldSpecified
            End Get
            Set
                Me.numeroFieldSpecified = value
                Me.RaisePropertyChanged("numeroSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property tipoLinea() As String
            Get
                Return Me.tipoLineaField
            End Get
            Set
                Me.tipoLineaField = value
                Me.RaisePropertyChanged("tipoLinea")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property tipoTelefono() As String
            Get
                Return Me.tipoTelefonoField
            End Get
            Set
                Me.tipoTelefonoField = value
                Me.RaisePropertyChanged("tipoTelefono")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class relacion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ffRelacionField As Date
        
        Private ffRelacionFieldSpecified As Boolean
        
        Private ffVencimientoField As Date
        
        Private ffVencimientoFieldSpecified As Boolean
        
        Private idPersonaField As Long
        
        Private idPersonaFieldSpecified As Boolean
        
        Private idPersonaAsociadaField As Long
        
        Private idPersonaAsociadaFieldSpecified As Boolean
        
        Private subtipoRelacionField As String
        
        Private tipoRelacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property ffRelacion() As Date
            Get
                Return Me.ffRelacionField
            End Get
            Set
                Me.ffRelacionField = value
                Me.RaisePropertyChanged("ffRelacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffRelacionSpecified() As Boolean
            Get
                Return Me.ffRelacionFieldSpecified
            End Get
            Set
                Me.ffRelacionFieldSpecified = value
                Me.RaisePropertyChanged("ffRelacionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property ffVencimiento() As Date
            Get
                Return Me.ffVencimientoField
            End Get
            Set
                Me.ffVencimientoField = value
                Me.RaisePropertyChanged("ffVencimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffVencimientoSpecified() As Boolean
            Get
                Return Me.ffVencimientoFieldSpecified
            End Get
            Set
                Me.ffVencimientoFieldSpecified = value
                Me.RaisePropertyChanged("ffVencimientoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property idPersona() As Long
            Get
                Return Me.idPersonaField
            End Get
            Set
                Me.idPersonaField = value
                Me.RaisePropertyChanged("idPersona")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaSpecified() As Boolean
            Get
                Return Me.idPersonaFieldSpecified
            End Get
            Set
                Me.idPersonaFieldSpecified = value
                Me.RaisePropertyChanged("idPersonaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property idPersonaAsociada() As Long
            Get
                Return Me.idPersonaAsociadaField
            End Get
            Set
                Me.idPersonaAsociadaField = value
                Me.RaisePropertyChanged("idPersonaAsociada")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaAsociadaSpecified() As Boolean
            Get
                Return Me.idPersonaAsociadaFieldSpecified
            End Get
            Set
                Me.idPersonaAsociadaFieldSpecified = value
                Me.RaisePropertyChanged("idPersonaAsociadaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property subtipoRelacion() As String
            Get
                Return Me.subtipoRelacionField
            End Get
            Set
                Me.subtipoRelacionField = value
                Me.RaisePropertyChanged("subtipoRelacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property tipoRelacion() As String
            Get
                Return Me.tipoRelacionField
            End Get
            Set
                Me.tipoRelacionField = value
                Me.RaisePropertyChanged("tipoRelacion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class regimen
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionRegimenField As String
        
        Private diaPeriodoField As Integer
        
        Private diaPeriodoFieldSpecified As Boolean
        
        Private estadoField As String
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private idRegimenField As Integer
        
        Private idRegimenFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        Private tipoRegimenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property descripcionRegimen() As String
            Get
                Return Me.descripcionRegimenField
            End Get
            Set
                Me.descripcionRegimenField = value
                Me.RaisePropertyChanged("descripcionRegimen")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property diaPeriodo() As Integer
            Get
                Return Me.diaPeriodoField
            End Get
            Set
                Me.diaPeriodoField = value
                Me.RaisePropertyChanged("diaPeriodo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property diaPeriodoSpecified() As Boolean
            Get
                Return Me.diaPeriodoFieldSpecified
            End Get
            Set
                Me.diaPeriodoFieldSpecified = value
                Me.RaisePropertyChanged("diaPeriodoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
                Me.RaisePropertyChanged("idImpuesto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
                Me.RaisePropertyChanged("idImpuestoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property idRegimen() As Integer
            Get
                Return Me.idRegimenField
            End Get
            Set
                Me.idRegimenField = value
                Me.RaisePropertyChanged("idRegimen")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idRegimenSpecified() As Boolean
            Get
                Return Me.idRegimenFieldSpecified
            End Get
            Set
                Me.idRegimenFieldSpecified = value
                Me.RaisePropertyChanged("idRegimenSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
                Me.RaisePropertyChanged("periodo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
                Me.RaisePropertyChanged("periodoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property tipoRegimen() As String
            Get
                Return Me.tipoRegimenField
            End Get
            Set
                Me.tipoRegimenField = value
                Me.RaisePropertyChanged("tipoRegimen")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class impuesto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionImpuestoField As String
        
        Private diaPeriodoField As Integer
        
        Private diaPeriodoFieldSpecified As Boolean
        
        Private estadoField As String
        
        Private ffInscripcionField As Date
        
        Private ffInscripcionFieldSpecified As Boolean
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property descripcionImpuesto() As String
            Get
                Return Me.descripcionImpuestoField
            End Get
            Set
                Me.descripcionImpuestoField = value
                Me.RaisePropertyChanged("descripcionImpuesto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property diaPeriodo() As Integer
            Get
                Return Me.diaPeriodoField
            End Get
            Set
                Me.diaPeriodoField = value
                Me.RaisePropertyChanged("diaPeriodo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property diaPeriodoSpecified() As Boolean
            Get
                Return Me.diaPeriodoFieldSpecified
            End Get
            Set
                Me.diaPeriodoFieldSpecified = value
                Me.RaisePropertyChanged("diaPeriodoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property ffInscripcion() As Date
            Get
                Return Me.ffInscripcionField
            End Get
            Set
                Me.ffInscripcionField = value
                Me.RaisePropertyChanged("ffInscripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffInscripcionSpecified() As Boolean
            Get
                Return Me.ffInscripcionFieldSpecified
            End Get
            Set
                Me.ffInscripcionFieldSpecified = value
                Me.RaisePropertyChanged("ffInscripcionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
                Me.RaisePropertyChanged("idImpuesto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
                Me.RaisePropertyChanged("idImpuestoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
                Me.RaisePropertyChanged("periodo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
                Me.RaisePropertyChanged("periodoSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class email
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private direccionField As String
        
        Private estadoField As String
        
        Private tipoEmailField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property tipoEmail() As String
            Get
                Return Me.tipoEmailField
            End Get
            Set
                Me.tipoEmailField = value
                Me.RaisePropertyChanged("tipoEmail")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class domicilio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codPostalField As String
        
        Private datoAdicionalField As String
        
        Private descripcionProvinciaField As String
        
        Private direccionField As String
        
        Private idProvinciaField As Integer
        
        Private idProvinciaFieldSpecified As Boolean
        
        Private localidadField As String
        
        Private ordenField As Integer
        
        Private ordenFieldSpecified As Boolean
        
        Private tipoDatoAdicionalField As String
        
        Private tipoDomicilioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property codPostal() As String
            Get
                Return Me.codPostalField
            End Get
            Set
                Me.codPostalField = value
                Me.RaisePropertyChanged("codPostal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property datoAdicional() As String
            Get
                Return Me.datoAdicionalField
            End Get
            Set
                Me.datoAdicionalField = value
                Me.RaisePropertyChanged("datoAdicional")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property descripcionProvincia() As String
            Get
                Return Me.descripcionProvinciaField
            End Get
            Set
                Me.descripcionProvinciaField = value
                Me.RaisePropertyChanged("descripcionProvincia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property idProvincia() As Integer
            Get
                Return Me.idProvinciaField
            End Get
            Set
                Me.idProvinciaField = value
                Me.RaisePropertyChanged("idProvincia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idProvinciaSpecified() As Boolean
            Get
                Return Me.idProvinciaFieldSpecified
            End Get
            Set
                Me.idProvinciaFieldSpecified = value
                Me.RaisePropertyChanged("idProvinciaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
                Me.RaisePropertyChanged("localidad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property orden() As Integer
            Get
                Return Me.ordenField
            End Get
            Set
                Me.ordenField = value
                Me.RaisePropertyChanged("orden")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ordenSpecified() As Boolean
            Get
                Return Me.ordenFieldSpecified
            End Get
            Set
                Me.ordenFieldSpecified = value
                Me.RaisePropertyChanged("ordenSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property tipoDatoAdicional() As String
            Get
                Return Me.tipoDatoAdicionalField
            End Get
            Set
                Me.tipoDatoAdicionalField = value
                Me.RaisePropertyChanged("tipoDatoAdicional")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property tipoDomicilio() As String
            Get
                Return Me.tipoDomicilioField
            End Get
            Set
                Me.tipoDomicilioField = value
                Me.RaisePropertyChanged("tipoDomicilio")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class dependencia
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionDependenciaField As String
        
        Private idDependenciaField As Integer
        
        Private idDependenciaFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property descripcionDependencia() As String
            Get
                Return Me.descripcionDependenciaField
            End Get
            Set
                Me.descripcionDependenciaField = value
                Me.RaisePropertyChanged("descripcionDependencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property idDependencia() As Integer
            Get
                Return Me.idDependenciaField
            End Get
            Set
                Me.idDependenciaField = value
                Me.RaisePropertyChanged("idDependencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idDependenciaSpecified() As Boolean
            Get
                Return Me.idDependenciaFieldSpecified
            End Get
            Set
                Me.idDependenciaFieldSpecified = value
                Me.RaisePropertyChanged("idDependenciaSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class categoria
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionCategoriaField As String
        
        Private estadoField As String
        
        Private idCategoriaField As Integer
        
        Private idCategoriaFieldSpecified As Boolean
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property descripcionCategoria() As String
            Get
                Return Me.descripcionCategoriaField
            End Get
            Set
                Me.descripcionCategoriaField = value
                Me.RaisePropertyChanged("descripcionCategoria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
                Me.RaisePropertyChanged("estado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property idCategoria() As Integer
            Get
                Return Me.idCategoriaField
            End Get
            Set
                Me.idCategoriaField = value
                Me.RaisePropertyChanged("idCategoria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idCategoriaSpecified() As Boolean
            Get
                Return Me.idCategoriaFieldSpecified
            End Get
            Set
                Me.idCategoriaFieldSpecified = value
                Me.RaisePropertyChanged("idCategoriaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
                Me.RaisePropertyChanged("idImpuesto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
                Me.RaisePropertyChanged("idImpuestoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
                Me.RaisePropertyChanged("periodo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
                Me.RaisePropertyChanged("periodoSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class actividad
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private descripcionActividadField As String
        
        Private idActividadField As Long
        
        Private idActividadFieldSpecified As Boolean
        
        Private nomencladorField As Integer
        
        Private nomencladorFieldSpecified As Boolean
        
        Private ordenField As Integer
        
        Private ordenFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property descripcionActividad() As String
            Get
                Return Me.descripcionActividadField
            End Get
            Set
                Me.descripcionActividadField = value
                Me.RaisePropertyChanged("descripcionActividad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property idActividad() As Long
            Get
                Return Me.idActividadField
            End Get
            Set
                Me.idActividadField = value
                Me.RaisePropertyChanged("idActividad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idActividadSpecified() As Boolean
            Get
                Return Me.idActividadFieldSpecified
            End Get
            Set
                Me.idActividadFieldSpecified = value
                Me.RaisePropertyChanged("idActividadSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property nomenclador() As Integer
            Get
                Return Me.nomencladorField
            End Get
            Set
                Me.nomencladorField = value
                Me.RaisePropertyChanged("nomenclador")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property nomencladorSpecified() As Boolean
            Get
                Return Me.nomencladorFieldSpecified
            End Get
            Set
                Me.nomencladorFieldSpecified = value
                Me.RaisePropertyChanged("nomencladorSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property orden() As Integer
            Get
                Return Me.ordenField
            End Get
            Set
                Me.ordenField = value
                Me.RaisePropertyChanged("orden")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ordenSpecified() As Boolean
            Get
                Return Me.ordenFieldSpecified
            End Get
            Set
                Me.ordenFieldSpecified = value
                Me.RaisePropertyChanged("ordenSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
                Me.RaisePropertyChanged("periodo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
                Me.RaisePropertyChanged("periodoSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class persona
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private actividadField() As actividad
        
        Private apellidoField As String
        
        Private cantidadSociosEmpresaMonoField As Integer
        
        Private cantidadSociosEmpresaMonoFieldSpecified As Boolean
        
        Private categoriaField() As categoria
        
        Private claveInactivaAsociadaField() As System.Nullable(Of Long)
        
        Private dependenciaField As dependencia
        
        Private domicilioField() As domicilio
        
        Private emailField() As email
        
        Private estadoClaveField As String
        
        Private fechaContratoSocialField As Date
        
        Private fechaContratoSocialFieldSpecified As Boolean
        
        Private fechaFallecimientoField As Date
        
        Private fechaFallecimientoFieldSpecified As Boolean
        
        Private fechaInscripcionField As Date
        
        Private fechaInscripcionFieldSpecified As Boolean
        
        Private fechaJubiladoField As Date
        
        Private fechaJubiladoFieldSpecified As Boolean
        
        Private fechaNacimientoField As Date
        
        Private fechaNacimientoFieldSpecified As Boolean
        
        Private fechaVencimientoMigracionField As Date
        
        Private fechaVencimientoMigracionFieldSpecified As Boolean
        
        Private formaJuridicaField As String
        
        Private idPersonaField As Long
        
        Private idPersonaFieldSpecified As Boolean
        
        Private impuestoField() As impuesto
        
        Private leyJubilacionField As Integer
        
        Private leyJubilacionFieldSpecified As Boolean
        
        Private localidadInscripcionField As String
        
        Private mesCierreField As Integer
        
        Private mesCierreFieldSpecified As Boolean
        
        Private nombreField As String
        
        Private numeroDocumentoField As String
        
        Private numeroInscripcionField As Long
        
        Private numeroInscripcionFieldSpecified As Boolean
        
        Private organismoInscripcionField As String
        
        Private organismoOriginanteField As String
        
        Private porcentajeCapitalNacionalField As Double
        
        Private porcentajeCapitalNacionalFieldSpecified As Boolean
        
        Private provinciaInscripcionField As String
        
        Private razonSocialField As String
        
        Private regimenField() As regimen
        
        Private relacionField() As relacion
        
        Private sexoField As String
        
        Private telefonoField() As telefono
        
        Private tipoClaveField As String
        
        Private tipoDocumentoField As String
        
        Private tipoOrganismoOriginanteField As String
        
        Private tipoPersonaField As String
        
        Private tipoResidenciaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("actividad", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property actividad() As actividad()
            Get
                Return Me.actividadField
            End Get
            Set
                Me.actividadField = value
                Me.RaisePropertyChanged("actividad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
                Me.RaisePropertyChanged("apellido")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property cantidadSociosEmpresaMono() As Integer
            Get
                Return Me.cantidadSociosEmpresaMonoField
            End Get
            Set
                Me.cantidadSociosEmpresaMonoField = value
                Me.RaisePropertyChanged("cantidadSociosEmpresaMono")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSociosEmpresaMonoSpecified() As Boolean
            Get
                Return Me.cantidadSociosEmpresaMonoFieldSpecified
            End Get
            Set
                Me.cantidadSociosEmpresaMonoFieldSpecified = value
                Me.RaisePropertyChanged("cantidadSociosEmpresaMonoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("categoria", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=3)>  _
        Public Property categoria() As categoria()
            Get
                Return Me.categoriaField
            End Get
            Set
                Me.categoriaField = value
                Me.RaisePropertyChanged("categoria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("claveInactivaAsociada", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=4)>  _
        Public Property claveInactivaAsociada() As System.Nullable(Of Long)()
            Get
                Return Me.claveInactivaAsociadaField
            End Get
            Set
                Me.claveInactivaAsociadaField = value
                Me.RaisePropertyChanged("claveInactivaAsociada")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property dependencia() As dependencia
            Get
                Return Me.dependenciaField
            End Get
            Set
                Me.dependenciaField = value
                Me.RaisePropertyChanged("dependencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("domicilio", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=6)>  _
        Public Property domicilio() As domicilio()
            Get
                Return Me.domicilioField
            End Get
            Set
                Me.domicilioField = value
                Me.RaisePropertyChanged("domicilio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("email", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=7)>  _
        Public Property email() As email()
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property estadoClave() As String
            Get
                Return Me.estadoClaveField
            End Get
            Set
                Me.estadoClaveField = value
                Me.RaisePropertyChanged("estadoClave")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property fechaContratoSocial() As Date
            Get
                Return Me.fechaContratoSocialField
            End Get
            Set
                Me.fechaContratoSocialField = value
                Me.RaisePropertyChanged("fechaContratoSocial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaContratoSocialSpecified() As Boolean
            Get
                Return Me.fechaContratoSocialFieldSpecified
            End Get
            Set
                Me.fechaContratoSocialFieldSpecified = value
                Me.RaisePropertyChanged("fechaContratoSocialSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property fechaFallecimiento() As Date
            Get
                Return Me.fechaFallecimientoField
            End Get
            Set
                Me.fechaFallecimientoField = value
                Me.RaisePropertyChanged("fechaFallecimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaFallecimientoSpecified() As Boolean
            Get
                Return Me.fechaFallecimientoFieldSpecified
            End Get
            Set
                Me.fechaFallecimientoFieldSpecified = value
                Me.RaisePropertyChanged("fechaFallecimientoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property fechaInscripcion() As Date
            Get
                Return Me.fechaInscripcionField
            End Get
            Set
                Me.fechaInscripcionField = value
                Me.RaisePropertyChanged("fechaInscripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaInscripcionSpecified() As Boolean
            Get
                Return Me.fechaInscripcionFieldSpecified
            End Get
            Set
                Me.fechaInscripcionFieldSpecified = value
                Me.RaisePropertyChanged("fechaInscripcionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property fechaJubilado() As Date
            Get
                Return Me.fechaJubiladoField
            End Get
            Set
                Me.fechaJubiladoField = value
                Me.RaisePropertyChanged("fechaJubilado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaJubiladoSpecified() As Boolean
            Get
                Return Me.fechaJubiladoFieldSpecified
            End Get
            Set
                Me.fechaJubiladoFieldSpecified = value
                Me.RaisePropertyChanged("fechaJubiladoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property fechaNacimiento() As Date
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
                Me.RaisePropertyChanged("fechaNacimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaNacimientoSpecified() As Boolean
            Get
                Return Me.fechaNacimientoFieldSpecified
            End Get
            Set
                Me.fechaNacimientoFieldSpecified = value
                Me.RaisePropertyChanged("fechaNacimientoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property fechaVencimientoMigracion() As Date
            Get
                Return Me.fechaVencimientoMigracionField
            End Get
            Set
                Me.fechaVencimientoMigracionField = value
                Me.RaisePropertyChanged("fechaVencimientoMigracion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaVencimientoMigracionSpecified() As Boolean
            Get
                Return Me.fechaVencimientoMigracionFieldSpecified
            End Get
            Set
                Me.fechaVencimientoMigracionFieldSpecified = value
                Me.RaisePropertyChanged("fechaVencimientoMigracionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property formaJuridica() As String
            Get
                Return Me.formaJuridicaField
            End Get
            Set
                Me.formaJuridicaField = value
                Me.RaisePropertyChanged("formaJuridica")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property idPersona() As Long
            Get
                Return Me.idPersonaField
            End Get
            Set
                Me.idPersonaField = value
                Me.RaisePropertyChanged("idPersona")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaSpecified() As Boolean
            Get
                Return Me.idPersonaFieldSpecified
            End Get
            Set
                Me.idPersonaFieldSpecified = value
                Me.RaisePropertyChanged("idPersonaSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("impuesto", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=17)>  _
        Public Property impuesto() As impuesto()
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
                Me.RaisePropertyChanged("impuesto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property leyJubilacion() As Integer
            Get
                Return Me.leyJubilacionField
            End Get
            Set
                Me.leyJubilacionField = value
                Me.RaisePropertyChanged("leyJubilacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property leyJubilacionSpecified() As Boolean
            Get
                Return Me.leyJubilacionFieldSpecified
            End Get
            Set
                Me.leyJubilacionFieldSpecified = value
                Me.RaisePropertyChanged("leyJubilacionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property localidadInscripcion() As String
            Get
                Return Me.localidadInscripcionField
            End Get
            Set
                Me.localidadInscripcionField = value
                Me.RaisePropertyChanged("localidadInscripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property mesCierre() As Integer
            Get
                Return Me.mesCierreField
            End Get
            Set
                Me.mesCierreField = value
                Me.RaisePropertyChanged("mesCierre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property mesCierreSpecified() As Boolean
            Get
                Return Me.mesCierreFieldSpecified
            End Get
            Set
                Me.mesCierreFieldSpecified = value
                Me.RaisePropertyChanged("mesCierreSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=21)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=22)>  _
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
                Me.RaisePropertyChanged("numeroDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=23)>  _
        Public Property numeroInscripcion() As Long
            Get
                Return Me.numeroInscripcionField
            End Get
            Set
                Me.numeroInscripcionField = value
                Me.RaisePropertyChanged("numeroInscripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroInscripcionSpecified() As Boolean
            Get
                Return Me.numeroInscripcionFieldSpecified
            End Get
            Set
                Me.numeroInscripcionFieldSpecified = value
                Me.RaisePropertyChanged("numeroInscripcionSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=24)>  _
        Public Property organismoInscripcion() As String
            Get
                Return Me.organismoInscripcionField
            End Get
            Set
                Me.organismoInscripcionField = value
                Me.RaisePropertyChanged("organismoInscripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=25)>  _
        Public Property organismoOriginante() As String
            Get
                Return Me.organismoOriginanteField
            End Get
            Set
                Me.organismoOriginanteField = value
                Me.RaisePropertyChanged("organismoOriginante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=26)>  _
        Public Property porcentajeCapitalNacional() As Double
            Get
                Return Me.porcentajeCapitalNacionalField
            End Get
            Set
                Me.porcentajeCapitalNacionalField = value
                Me.RaisePropertyChanged("porcentajeCapitalNacional")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentajeCapitalNacionalSpecified() As Boolean
            Get
                Return Me.porcentajeCapitalNacionalFieldSpecified
            End Get
            Set
                Me.porcentajeCapitalNacionalFieldSpecified = value
                Me.RaisePropertyChanged("porcentajeCapitalNacionalSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=27)>  _
        Public Property provinciaInscripcion() As String
            Get
                Return Me.provinciaInscripcionField
            End Get
            Set
                Me.provinciaInscripcionField = value
                Me.RaisePropertyChanged("provinciaInscripcion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=28)>  _
        Public Property razonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
                Me.RaisePropertyChanged("razonSocial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("regimen", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=29)>  _
        Public Property regimen() As regimen()
            Get
                Return Me.regimenField
            End Get
            Set
                Me.regimenField = value
                Me.RaisePropertyChanged("regimen")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("relacion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=30)>  _
        Public Property relacion() As relacion()
            Get
                Return Me.relacionField
            End Get
            Set
                Me.relacionField = value
                Me.RaisePropertyChanged("relacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=31)>  _
        Public Property sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
                Me.RaisePropertyChanged("sexo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("telefono", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=32)>  _
        Public Property telefono() As telefono()
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
                Me.RaisePropertyChanged("telefono")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=33)>  _
        Public Property tipoClave() As String
            Get
                Return Me.tipoClaveField
            End Get
            Set
                Me.tipoClaveField = value
                Me.RaisePropertyChanged("tipoClave")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=34)>  _
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
                Me.RaisePropertyChanged("tipoDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=35)>  _
        Public Property tipoOrganismoOriginante() As String
            Get
                Return Me.tipoOrganismoOriginanteField
            End Get
            Set
                Me.tipoOrganismoOriginanteField = value
                Me.RaisePropertyChanged("tipoOrganismoOriginante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=36)>  _
        Public Property tipoPersona() As String
            Get
                Return Me.tipoPersonaField
            End Get
            Set
                Me.tipoPersonaField = value
                Me.RaisePropertyChanged("tipoPersona")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=37)>  _
        Public Property tipoResidencia() As String
            Get
                Return Me.tipoResidenciaField
            End Get
            Set
                Me.tipoResidenciaField = value
                Me.RaisePropertyChanged("tipoResidencia")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class metadata
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fechaHoraField As Date
        
        Private fechaHoraFieldSpecified As Boolean
        
        Private servidorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property fechaHora() As Date
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
                Me.RaisePropertyChanged("fechaHora")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaHoraSpecified() As Boolean
            Get
                Return Me.fechaHoraFieldSpecified
            End Get
            Set
                Me.fechaHoraFieldSpecified = value
                Me.RaisePropertyChanged("fechaHoraSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property servidor() As String
            Get
                Return Me.servidorField
            End Get
            Set
                Me.servidorField = value
                Me.RaisePropertyChanged("servidor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class personaReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private metadataField As metadata
        
        Private personaField As persona
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property metadata() As metadata
            Get
                Return Me.metadataField
            End Get
            Set
                Me.metadataField = value
                Me.RaisePropertyChanged("metadata")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property persona() As persona
            Get
                Return Me.personaField
            End Get
            Set
                Me.personaField = value
                Me.RaisePropertyChanged("persona")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class dummyReturn
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private appserverField As String
        
        Private authserverField As String
        
        Private dbserverField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property appserver() As String
            Get
                Return Me.appserverField
            End Get
            Set
                Me.appserverField = value
                Me.RaisePropertyChanged("appserver")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property authserver() As String
            Get
                Return Me.authserverField
            End Get
            Set
                Me.authserverField = value
                Me.RaisePropertyChanged("authserver")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property dbserver() As String
            Get
                Return Me.dbserverField
            End Get
            Set
                Me.dbserverField = value
                Me.RaisePropertyChanged("dbserver")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", ConfigurationName:="WsPersonas_Homo.PersonaServiceA4")>  _
    Public Interface PersonaServiceA4
        
        'CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function dummy(ByVal request As WsPersonas_Homo.dummy) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> WsPersonas_Homo.dummyResponse
        
        'CODEGEN: El parámetro 'personaReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WsPersonas_Homo.SRValidationException), Action:="", Name:="SRValidationException"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getPersona(ByVal request As WsPersonas_Homo.getPersona) As <System.ServiceModel.MessageParameterAttribute(Name:="personaReturn")> WsPersonas_Homo.getPersonaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="dummy", WrapperNamespace:="http://a4.soap.ws.server.puc.sr/", IsWrapped:=true)>  _
    Partial Public Class dummy
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="dummyResponse", WrapperNamespace:="http://a4.soap.ws.server.puc.sr/", IsWrapped:=true)>  _
    Partial Public Class dummyResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As WsPersonas_Homo.dummyReturn
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As WsPersonas_Homo.dummyReturn)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPersona", WrapperNamespace:="http://a4.soap.ws.server.puc.sr/", IsWrapped:=true)>  _
    Partial Public Class getPersona
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public token As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public sign As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public cuitRepresentada As Long
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idPersona As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona As Long)
            MyBase.New
            Me.token = token
            Me.sign = sign
            Me.cuitRepresentada = cuitRepresentada
            Me.idPersona = idPersona
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPersonaResponse", WrapperNamespace:="http://a4.soap.ws.server.puc.sr/", IsWrapped:=true)>  _
    Partial Public Class getPersonaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public personaReturn As WsPersonas_Homo.personaReturn
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal personaReturn As WsPersonas_Homo.personaReturn)
            MyBase.New
            Me.personaReturn = personaReturn
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PersonaServiceA4Channel
        Inherits WsPersonas_Homo.PersonaServiceA4, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PersonaServiceA4Client
        Inherits System.ServiceModel.ClientBase(Of WsPersonas_Homo.PersonaServiceA4)
        Implements WsPersonas_Homo.PersonaServiceA4
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsPersonas_Homo_PersonaServiceA4_dummy(ByVal request As WsPersonas_Homo.dummy) As WsPersonas_Homo.dummyResponse Implements WsPersonas_Homo.PersonaServiceA4.dummy
            Return MyBase.Channel.dummy(request)
        End Function
        
        Public Function dummy() As WsPersonas_Homo.dummyReturn
            Dim inValue As WsPersonas_Homo.dummy = New WsPersonas_Homo.dummy()
            Dim retVal As WsPersonas_Homo.dummyResponse = CType(Me,WsPersonas_Homo.PersonaServiceA4).dummy(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsPersonas_Homo_PersonaServiceA4_getPersona(ByVal request As WsPersonas_Homo.getPersona) As WsPersonas_Homo.getPersonaResponse Implements WsPersonas_Homo.PersonaServiceA4.getPersona
            Return MyBase.Channel.getPersona(request)
        End Function
        
        Public Function getPersona(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona As Long) As WsPersonas_Homo.personaReturn
            Dim inValue As WsPersonas_Homo.getPersona = New WsPersonas_Homo.getPersona()
            inValue.token = token
            inValue.sign = sign
            inValue.cuitRepresentada = cuitRepresentada
            inValue.idPersona = idPersona
            Dim retVal As WsPersonas_Homo.getPersonaResponse = CType(Me,WsPersonas_Homo.PersonaServiceA4).getPersona(inValue)
            Return retVal.personaReturn
        End Function
    End Class
End Namespace
