//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardSoft.PersonasA5Prod {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class SRValidationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class metadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        private string servidorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified {
            get {
                return this.fechaHoraFieldSpecified;
            }
            set {
                this.fechaHoraFieldSpecified = value;
                this.RaisePropertyChanged("fechaHoraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string servidor {
            get {
                return this.servidorField;
            }
            set {
                this.servidorField = value;
                this.RaisePropertyChanged("servidor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class errorRegimenGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class errorMonotributo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class errorConstancia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string[] errorField;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class regimen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionRegimenField;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int idRegimenField;
        
        private bool idRegimenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        private string tipoRegimenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionRegimen {
            get {
                return this.descripcionRegimenField;
            }
            set {
                this.descripcionRegimenField = value;
                this.RaisePropertyChanged("descripcionRegimen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
                this.RaisePropertyChanged("idImpuesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
                this.RaisePropertyChanged("idImpuestoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idRegimen {
            get {
                return this.idRegimenField;
            }
            set {
                this.idRegimenField = value;
                this.RaisePropertyChanged("idRegimen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegimenSpecified {
            get {
                return this.idRegimenFieldSpecified;
            }
            set {
                this.idRegimenFieldSpecified = value;
                this.RaisePropertyChanged("idRegimenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
                this.RaisePropertyChanged("periodoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoRegimen {
            get {
                return this.tipoRegimenField;
            }
            set {
                this.tipoRegimenField = value;
                this.RaisePropertyChanged("tipoRegimen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class datosRegimenGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad[] actividadField;
        
        private categoria categoriaAutonomoField;
        
        private impuesto[] impuestoField;
        
        private regimen[] regimenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividad[] actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoria categoriaAutonomo {
            get {
                return this.categoriaAutonomoField;
            }
            set {
                this.categoriaAutonomoField = value;
                this.RaisePropertyChanged("categoriaAutonomo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public impuesto[] impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regimen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public regimen[] regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
                this.RaisePropertyChanged("regimen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionActividadField;
        
        private long idActividadField;
        
        private bool idActividadFieldSpecified;
        
        private int nomencladorField;
        
        private bool nomencladorFieldSpecified;
        
        private int ordenField;
        
        private bool ordenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionActividad {
            get {
                return this.descripcionActividadField;
            }
            set {
                this.descripcionActividadField = value;
                this.RaisePropertyChanged("descripcionActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("idActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idActividadSpecified {
            get {
                return this.idActividadFieldSpecified;
            }
            set {
                this.idActividadFieldSpecified = value;
                this.RaisePropertyChanged("idActividadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int nomenclador {
            get {
                return this.nomencladorField;
            }
            set {
                this.nomencladorField = value;
                this.RaisePropertyChanged("nomenclador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomencladorSpecified {
            get {
                return this.nomencladorFieldSpecified;
            }
            set {
                this.nomencladorFieldSpecified = value;
                this.RaisePropertyChanged("nomencladorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified {
            get {
                return this.ordenFieldSpecified;
            }
            set {
                this.ordenFieldSpecified = value;
                this.RaisePropertyChanged("ordenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
                this.RaisePropertyChanged("periodoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionCategoriaField;
        
        private int idCategoriaField;
        
        private bool idCategoriaFieldSpecified;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                this.descripcionCategoriaField = value;
                this.RaisePropertyChanged("descripcionCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified {
            get {
                return this.idCategoriaFieldSpecified;
            }
            set {
                this.idCategoriaFieldSpecified = value;
                this.RaisePropertyChanged("idCategoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
                this.RaisePropertyChanged("idImpuesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
                this.RaisePropertyChanged("idImpuestoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
                this.RaisePropertyChanged("periodoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class impuesto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionImpuestoField;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionImpuesto {
            get {
                return this.descripcionImpuestoField;
            }
            set {
                this.descripcionImpuestoField = value;
                this.RaisePropertyChanged("descripcionImpuesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
                this.RaisePropertyChanged("idImpuesto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
                this.RaisePropertyChanged("idImpuestoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
                this.RaisePropertyChanged("periodoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class relacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoPersonaAsociadaField;
        
        private System.DateTime ffRelacionField;
        
        private bool ffRelacionFieldSpecified;
        
        private System.DateTime ffVencimientoField;
        
        private bool ffVencimientoFieldSpecified;
        
        private long idPersonaAsociadaField;
        
        private bool idPersonaAsociadaFieldSpecified;
        
        private string nombrePersonaAsociadaField;
        
        private string razonSocialPersonaAsociadaField;
        
        private string tipoComponenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPersonaAsociada {
            get {
                return this.apellidoPersonaAsociadaField;
            }
            set {
                this.apellidoPersonaAsociadaField = value;
                this.RaisePropertyChanged("apellidoPersonaAsociada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime ffRelacion {
            get {
                return this.ffRelacionField;
            }
            set {
                this.ffRelacionField = value;
                this.RaisePropertyChanged("ffRelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffRelacionSpecified {
            get {
                return this.ffRelacionFieldSpecified;
            }
            set {
                this.ffRelacionFieldSpecified = value;
                this.RaisePropertyChanged("ffRelacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime ffVencimiento {
            get {
                return this.ffVencimientoField;
            }
            set {
                this.ffVencimientoField = value;
                this.RaisePropertyChanged("ffVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffVencimientoSpecified {
            get {
                return this.ffVencimientoFieldSpecified;
            }
            set {
                this.ffVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("ffVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idPersonaAsociada {
            get {
                return this.idPersonaAsociadaField;
            }
            set {
                this.idPersonaAsociadaField = value;
                this.RaisePropertyChanged("idPersonaAsociada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaAsociadaSpecified {
            get {
                return this.idPersonaAsociadaFieldSpecified;
            }
            set {
                this.idPersonaAsociadaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaAsociadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombrePersonaAsociada {
            get {
                return this.nombrePersonaAsociadaField;
            }
            set {
                this.nombrePersonaAsociadaField = value;
                this.RaisePropertyChanged("nombrePersonaAsociada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string razonSocialPersonaAsociada {
            get {
                return this.razonSocialPersonaAsociadaField;
            }
            set {
                this.razonSocialPersonaAsociadaField = value;
                this.RaisePropertyChanged("razonSocialPersonaAsociada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoComponente {
            get {
                return this.tipoComponenteField;
            }
            set {
                this.tipoComponenteField = value;
                this.RaisePropertyChanged("tipoComponente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class datosMonotributo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad[] actividadField;
        
        private actividad actividadMonotributistaField;
        
        private categoria categoriaMonotributoField;
        
        private relacion[] componenteDeSociedadField;
        
        private impuesto[] impuestoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividad[] actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
                this.RaisePropertyChanged("actividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public actividad actividadMonotributista {
            get {
                return this.actividadMonotributistaField;
            }
            set {
                this.actividadMonotributistaField = value;
                this.RaisePropertyChanged("actividadMonotributista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public categoria categoriaMonotributo {
            get {
                return this.categoriaMonotributoField;
            }
            set {
                this.categoriaMonotributoField = value;
                this.RaisePropertyChanged("categoriaMonotributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("componenteDeSociedad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public relacion[] componenteDeSociedad {
            get {
                return this.componenteDeSociedadField;
            }
            set {
                this.componenteDeSociedadField = value;
                this.RaisePropertyChanged("componenteDeSociedad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public impuesto[] impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
                this.RaisePropertyChanged("impuesto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class domicilio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codPostalField;
        
        private string datoAdicionalField;
        
        private string descripcionProvinciaField;
        
        private string direccionField;
        
        private int idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string localidadField;
        
        private string tipoDatoAdicionalField;
        
        private string tipoDomicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
                this.RaisePropertyChanged("codPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string datoAdicional {
            get {
                return this.datoAdicionalField;
            }
            set {
                this.datoAdicionalField = value;
                this.RaisePropertyChanged("datoAdicional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionProvincia {
            get {
                return this.descripcionProvinciaField;
            }
            set {
                this.descripcionProvinciaField = value;
                this.RaisePropertyChanged("descripcionProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
                this.RaisePropertyChanged("idProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
                this.RaisePropertyChanged("idProvinciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDatoAdicional {
            get {
                return this.tipoDatoAdicionalField;
            }
            set {
                this.tipoDatoAdicionalField = value;
                this.RaisePropertyChanged("tipoDatoAdicional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tipoDomicilio {
            get {
                return this.tipoDomicilioField;
            }
            set {
                this.tipoDomicilioField = value;
                this.RaisePropertyChanged("tipoDomicilio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class dependencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codPostalField;
        
        private string descripcionDependenciaField;
        
        private string descripcionProvinciaField;
        
        private string direccionField;
        
        private int idDependenciaField;
        
        private bool idDependenciaFieldSpecified;
        
        private int idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string localidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
                this.RaisePropertyChanged("codPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionDependencia {
            get {
                return this.descripcionDependenciaField;
            }
            set {
                this.descripcionDependenciaField = value;
                this.RaisePropertyChanged("descripcionDependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionProvincia {
            get {
                return this.descripcionProvinciaField;
            }
            set {
                this.descripcionProvinciaField = value;
                this.RaisePropertyChanged("descripcionProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idDependencia {
            get {
                return this.idDependenciaField;
            }
            set {
                this.idDependenciaField = value;
                this.RaisePropertyChanged("idDependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDependenciaSpecified {
            get {
                return this.idDependenciaFieldSpecified;
            }
            set {
                this.idDependenciaFieldSpecified = value;
                this.RaisePropertyChanged("idDependenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
                this.RaisePropertyChanged("idProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
                this.RaisePropertyChanged("idProvinciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class caracterizacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionCaracterizacionField;
        
        private int idCaracterizacionField;
        
        private bool idCaracterizacionFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionCaracterizacion {
            get {
                return this.descripcionCaracterizacionField;
            }
            set {
                this.descripcionCaracterizacionField = value;
                this.RaisePropertyChanged("descripcionCaracterizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCaracterizacion {
            get {
                return this.idCaracterizacionField;
            }
            set {
                this.idCaracterizacionField = value;
                this.RaisePropertyChanged("idCaracterizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCaracterizacionSpecified {
            get {
                return this.idCaracterizacionFieldSpecified;
            }
            set {
                this.idCaracterizacionFieldSpecified = value;
                this.RaisePropertyChanged("idCaracterizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
                this.RaisePropertyChanged("periodoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class datosGenerales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private caracterizacion[] caracterizacionField;
        
        private dependencia dependenciaField;
        
        private domicilio domicilioFiscalField;
        
        private string estadoClaveField;
        
        private System.DateTime fechaContratoSocialField;
        
        private bool fechaContratoSocialFieldSpecified;
        
        private System.DateTime fechaFallecimientoField;
        
        private bool fechaFallecimientoFieldSpecified;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private int mesCierreField;
        
        private bool mesCierreFieldSpecified;
        
        private string nombreField;
        
        private string razonSocialField;
        
        private string tipoClaveField;
        
        private string tipoPersonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("caracterizacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public caracterizacion[] caracterizacion {
            get {
                return this.caracterizacionField;
            }
            set {
                this.caracterizacionField = value;
                this.RaisePropertyChanged("caracterizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public dependencia dependencia {
            get {
                return this.dependenciaField;
            }
            set {
                this.dependenciaField = value;
                this.RaisePropertyChanged("dependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public domicilio domicilioFiscal {
            get {
                return this.domicilioFiscalField;
            }
            set {
                this.domicilioFiscalField = value;
                this.RaisePropertyChanged("domicilioFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string estadoClave {
            get {
                return this.estadoClaveField;
            }
            set {
                this.estadoClaveField = value;
                this.RaisePropertyChanged("estadoClave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaContratoSocial {
            get {
                return this.fechaContratoSocialField;
            }
            set {
                this.fechaContratoSocialField = value;
                this.RaisePropertyChanged("fechaContratoSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoSocialSpecified {
            get {
                return this.fechaContratoSocialFieldSpecified;
            }
            set {
                this.fechaContratoSocialFieldSpecified = value;
                this.RaisePropertyChanged("fechaContratoSocialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaFallecimiento {
            get {
                return this.fechaFallecimientoField;
            }
            set {
                this.fechaFallecimientoField = value;
                this.RaisePropertyChanged("fechaFallecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFallecimientoSpecified {
            get {
                return this.fechaFallecimientoFieldSpecified;
            }
            set {
                this.fechaFallecimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFallecimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int mesCierre {
            get {
                return this.mesCierreField;
            }
            set {
                this.mesCierreField = value;
                this.RaisePropertyChanged("mesCierre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesCierreSpecified {
            get {
                return this.mesCierreFieldSpecified;
            }
            set {
                this.mesCierreFieldSpecified = value;
                this.RaisePropertyChanged("mesCierreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tipoClave {
            get {
                return this.tipoClaveField;
            }
            set {
                this.tipoClaveField = value;
                this.RaisePropertyChanged("tipoClave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
                this.RaisePropertyChanged("tipoPersona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class personaReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosGenerales datosGeneralesField;
        
        private datosMonotributo datosMonotributoField;
        
        private datosRegimenGeneral datosRegimenGeneralField;
        
        private errorConstancia errorConstanciaField;
        
        private errorMonotributo errorMonotributoField;
        
        private errorRegimenGeneral errorRegimenGeneralField;
        
        private metadata metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public datosGenerales datosGenerales {
            get {
                return this.datosGeneralesField;
            }
            set {
                this.datosGeneralesField = value;
                this.RaisePropertyChanged("datosGenerales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public datosMonotributo datosMonotributo {
            get {
                return this.datosMonotributoField;
            }
            set {
                this.datosMonotributoField = value;
                this.RaisePropertyChanged("datosMonotributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public datosRegimenGeneral datosRegimenGeneral {
            get {
                return this.datosRegimenGeneralField;
            }
            set {
                this.datosRegimenGeneralField = value;
                this.RaisePropertyChanged("datosRegimenGeneral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorConstancia errorConstancia {
            get {
                return this.errorConstanciaField;
            }
            set {
                this.errorConstanciaField = value;
                this.RaisePropertyChanged("errorConstancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public errorMonotributo errorMonotributo {
            get {
                return this.errorMonotributoField;
            }
            set {
                this.errorMonotributoField = value;
                this.RaisePropertyChanged("errorMonotributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public errorRegimenGeneral errorRegimenGeneral {
            get {
                return this.errorRegimenGeneralField;
            }
            set {
                this.errorRegimenGeneralField = value;
                this.RaisePropertyChanged("errorRegimenGeneral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", ConfigurationName="PersonasA5Prod.PersonaServiceA5")]
    public interface PersonaServiceA5 {
        
        // CODEGEN: El parámetro 'personaReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HardSoft.PersonasA5Prod.SRValidationException), Action="", Name="SRValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="personaReturn")]
        HardSoft.PersonasA5Prod.getPersonaResponse getPersona(HardSoft.PersonasA5Prod.getPersona request);
        
        // CODEGEN: El parámetro 'personaListReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HardSoft.PersonasA5Prod.SRValidationException), Action="", Name="SRValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="personaListReturn")]
        HardSoft.PersonasA5Prod.getPersonaListResponse getPersonaList(HardSoft.PersonasA5Prod.getPersonaList request);
        
        // CODEGEN: El parámetro 'personaReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HardSoft.PersonasA5Prod.SRValidationException), Action="", Name="SRValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="personaReturn")]
        HardSoft.PersonasA5Prod.getPersona_v2Response getPersona_v2(HardSoft.PersonasA5Prod.getPersona_v2 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HardSoft.PersonasA5Prod.dummyResponse dummy(HardSoft.PersonasA5Prod.dummy request);
        
        // CODEGEN: El parámetro 'personaListReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(HardSoft.PersonasA5Prod.SRValidationException), Action="", Name="SRValidationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="personaListReturn")]
        HardSoft.PersonasA5Prod.getPersonaList_v2Response getPersonaList_v2(HardSoft.PersonasA5Prod.getPersonaList_v2 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersona", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersona {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitRepresentada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona;
        
        public getPersona() {
        }
        
        public getPersona(string token, string sign, long cuitRepresentada, long idPersona) {
            this.token = token;
            this.sign = sign;
            this.cuitRepresentada = cuitRepresentada;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaResponse", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HardSoft.PersonasA5Prod.personaReturn personaReturn;
        
        public getPersonaResponse() {
        }
        
        public getPersonaResponse(HardSoft.PersonasA5Prod.personaReturn personaReturn) {
            this.personaReturn = personaReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class personaListReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private metadata metadataField;
        
        private persona[] personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public persona[] persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosGenerales datosGeneralesField;
        
        private datosMonotributo datosMonotributoField;
        
        private datosRegimenGeneral datosRegimenGeneralField;
        
        private errorConstancia errorConstanciaField;
        
        private errorMonotributo errorMonotributoField;
        
        private errorRegimenGeneral errorRegimenGeneralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public datosGenerales datosGenerales {
            get {
                return this.datosGeneralesField;
            }
            set {
                this.datosGeneralesField = value;
                this.RaisePropertyChanged("datosGenerales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public datosMonotributo datosMonotributo {
            get {
                return this.datosMonotributoField;
            }
            set {
                this.datosMonotributoField = value;
                this.RaisePropertyChanged("datosMonotributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public datosRegimenGeneral datosRegimenGeneral {
            get {
                return this.datosRegimenGeneralField;
            }
            set {
                this.datosRegimenGeneralField = value;
                this.RaisePropertyChanged("datosRegimenGeneral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public errorConstancia errorConstancia {
            get {
                return this.errorConstanciaField;
            }
            set {
                this.errorConstanciaField = value;
                this.RaisePropertyChanged("errorConstancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public errorMonotributo errorMonotributo {
            get {
                return this.errorMonotributoField;
            }
            set {
                this.errorMonotributoField = value;
                this.RaisePropertyChanged("errorMonotributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public errorRegimenGeneral errorRegimenGeneral {
            get {
                return this.errorRegimenGeneralField;
            }
            set {
                this.errorRegimenGeneralField = value;
                this.RaisePropertyChanged("errorRegimenGeneral");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaList", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersonaList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitRepresentada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] idPersona;
        
        public getPersonaList() {
        }
        
        public getPersonaList(string token, string sign, long cuitRepresentada, long[] idPersona) {
            this.token = token;
            this.sign = sign;
            this.cuitRepresentada = cuitRepresentada;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaListResponse", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersonaListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HardSoft.PersonasA5Prod.personaListReturn personaListReturn;
        
        public getPersonaListResponse() {
        }
        
        public getPersonaListResponse(HardSoft.PersonasA5Prod.personaListReturn personaListReturn) {
            this.personaListReturn = personaListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersona_v2", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersona_v2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitRepresentada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona;
        
        public getPersona_v2() {
        }
        
        public getPersona_v2(string token, string sign, long cuitRepresentada, long idPersona) {
            this.token = token;
            this.sign = sign;
            this.cuitRepresentada = cuitRepresentada;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersona_v2Response", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersona_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HardSoft.PersonasA5Prod.personaReturn personaReturn;
        
        public getPersona_v2Response() {
        }
        
        public getPersona_v2Response(HardSoft.PersonasA5Prod.personaReturn personaReturn) {
            this.personaReturn = personaReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class dummyReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appserverField;
        
        private string authserverField;
        
        private string dbserverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appserver {
            get {
                return this.appserverField;
            }
            set {
                this.appserverField = value;
                this.RaisePropertyChanged("appserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string authserver {
            get {
                return this.authserverField;
            }
            set {
                this.authserverField = value;
                this.RaisePropertyChanged("authserver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dbserver {
            get {
                return this.dbserverField;
            }
            set {
                this.dbserverField = value;
                this.RaisePropertyChanged("dbserver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dummy", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class dummy {
        
        public dummy() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dummyResponse", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class dummyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HardSoft.PersonasA5Prod.dummyReturn @return;
        
        public dummyResponse() {
        }
        
        public dummyResponse(HardSoft.PersonasA5Prod.dummyReturn @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaList_v2", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersonaList_v2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long cuitRepresentada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] idPersona;
        
        public getPersonaList_v2() {
        }
        
        public getPersonaList_v2(string token, string sign, long cuitRepresentada, long[] idPersona) {
            this.token = token;
            this.sign = sign;
            this.cuitRepresentada = cuitRepresentada;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonaList_v2Response", WrapperNamespace="http://a5.soap.ws.server.puc.sr/", IsWrapped=true)]
    public partial class getPersonaList_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://a5.soap.ws.server.puc.sr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HardSoft.PersonasA5Prod.personaListReturn personaListReturn;
        
        public getPersonaList_v2Response() {
        }
        
        public getPersonaList_v2Response(HardSoft.PersonasA5Prod.personaListReturn personaListReturn) {
            this.personaListReturn = personaListReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonaServiceA5Channel : HardSoft.PersonasA5Prod.PersonaServiceA5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaServiceA5Client : System.ServiceModel.ClientBase<HardSoft.PersonasA5Prod.PersonaServiceA5>, HardSoft.PersonasA5Prod.PersonaServiceA5 {
        
        public PersonaServiceA5Client() {
        }
        
        public PersonaServiceA5Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaServiceA5Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceA5Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceA5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HardSoft.PersonasA5Prod.getPersonaResponse HardSoft.PersonasA5Prod.PersonaServiceA5.getPersona(HardSoft.PersonasA5Prod.getPersona request) {
            return base.Channel.getPersona(request);
        }
        
        public HardSoft.PersonasA5Prod.personaReturn getPersona(string token, string sign, long cuitRepresentada, long idPersona) {
            HardSoft.PersonasA5Prod.getPersona inValue = new HardSoft.PersonasA5Prod.getPersona();
            inValue.token = token;
            inValue.sign = sign;
            inValue.cuitRepresentada = cuitRepresentada;
            inValue.idPersona = idPersona;
            HardSoft.PersonasA5Prod.getPersonaResponse retVal = ((HardSoft.PersonasA5Prod.PersonaServiceA5)(this)).getPersona(inValue);
            return retVal.personaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HardSoft.PersonasA5Prod.getPersonaListResponse HardSoft.PersonasA5Prod.PersonaServiceA5.getPersonaList(HardSoft.PersonasA5Prod.getPersonaList request) {
            return base.Channel.getPersonaList(request);
        }
        
        public HardSoft.PersonasA5Prod.personaListReturn getPersonaList(string token, string sign, long cuitRepresentada, long[] idPersona) {
            HardSoft.PersonasA5Prod.getPersonaList inValue = new HardSoft.PersonasA5Prod.getPersonaList();
            inValue.token = token;
            inValue.sign = sign;
            inValue.cuitRepresentada = cuitRepresentada;
            inValue.idPersona = idPersona;
            HardSoft.PersonasA5Prod.getPersonaListResponse retVal = ((HardSoft.PersonasA5Prod.PersonaServiceA5)(this)).getPersonaList(inValue);
            return retVal.personaListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HardSoft.PersonasA5Prod.getPersona_v2Response HardSoft.PersonasA5Prod.PersonaServiceA5.getPersona_v2(HardSoft.PersonasA5Prod.getPersona_v2 request) {
            return base.Channel.getPersona_v2(request);
        }
        
        public HardSoft.PersonasA5Prod.personaReturn getPersona_v2(string token, string sign, long cuitRepresentada, long idPersona) {
            HardSoft.PersonasA5Prod.getPersona_v2 inValue = new HardSoft.PersonasA5Prod.getPersona_v2();
            inValue.token = token;
            inValue.sign = sign;
            inValue.cuitRepresentada = cuitRepresentada;
            inValue.idPersona = idPersona;
            HardSoft.PersonasA5Prod.getPersona_v2Response retVal = ((HardSoft.PersonasA5Prod.PersonaServiceA5)(this)).getPersona_v2(inValue);
            return retVal.personaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HardSoft.PersonasA5Prod.dummyResponse HardSoft.PersonasA5Prod.PersonaServiceA5.dummy(HardSoft.PersonasA5Prod.dummy request) {
            return base.Channel.dummy(request);
        }
        
        public HardSoft.PersonasA5Prod.dummyReturn dummy() {
            HardSoft.PersonasA5Prod.dummy inValue = new HardSoft.PersonasA5Prod.dummy();
            HardSoft.PersonasA5Prod.dummyResponse retVal = ((HardSoft.PersonasA5Prod.PersonaServiceA5)(this)).dummy(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HardSoft.PersonasA5Prod.getPersonaList_v2Response HardSoft.PersonasA5Prod.PersonaServiceA5.getPersonaList_v2(HardSoft.PersonasA5Prod.getPersonaList_v2 request) {
            return base.Channel.getPersonaList_v2(request);
        }
        
        public HardSoft.PersonasA5Prod.personaListReturn getPersonaList_v2(string token, string sign, long cuitRepresentada, long[] idPersona) {
            HardSoft.PersonasA5Prod.getPersonaList_v2 inValue = new HardSoft.PersonasA5Prod.getPersonaList_v2();
            inValue.token = token;
            inValue.sign = sign;
            inValue.cuitRepresentada = cuitRepresentada;
            inValue.idPersona = idPersona;
            HardSoft.PersonasA5Prod.getPersonaList_v2Response retVal = ((HardSoft.PersonasA5Prod.PersonaServiceA5)(this)).getPersonaList_v2(inValue);
            return retVal.personaListReturn;
        }
    }
}
